version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    image: nodejs
    container_name: nodejs
    ports:
      - '3000:5000'
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules